Added CollectionView ItemSwipe
telerik/maui-docs pull request #883
Opened 2024-07-21 20:11 UTC by kerpecheva

2024-07-23 12:12 UTC, ikoevska requested changes
Same issue as with drag-and-drop. You need to fix the config.yml to render the section name properly.

![image](https://github.com/user-attachments/assets/ee034f84-ec23-4f31-9c6f-f3ff555eacda)

2024-07-23 12:12 UTC, ikoevska commented on controls/collectionview/item-swipe/overview.md
> +You can use the following `RadCollectionView` properties to configure the Item Swipe feature:
```suggestion
You can use the following `RadCollectionView` properties to configure the item swipe feature:
```

2024-07-23 12:12 UTC, ikoevska commented on controls/collectionview/item-swipe/overview.md
> +- `EndSwipeTemplate`(`DataTemplate`)&mdash;Defines the content that is visualized when swipe is performed to right in vertical orientation or down in horizontal orientation.
```suggestion
- `EndSwipeTemplate`(`DataTemplate`)&mdash;Defines the content that is visualized for a swipe-right (in vertical orientations) or a swipe-down (in horizontal orientations).
```

2024-07-23 12:12 UTC, ikoevska commented on controls/collectionview/item-swipe/item-swipe-events.md
> +- `SwipeStarting`&mdash;Occurs when item is about to be swiped. The event arguments are of the `CollectionViewSwipeStartingEventArgs` type that provides the following properties:
```suggestion
- `SwipeStarting`&mdash;Occurs when an item is about to be swiped. The event arguments are of the `CollectionViewSwipeStartingEventArgs` type that provides the following properties:
```

2024-07-23 12:12 UTC, ikoevska commented on controls/collectionview/item-swipe/item-swipe-events.md
> +- `SwipeCompleted`&mdash;Occurs when swiping of an item is completed. The event arguments are of the `CollectionViewSwipeCompletedEventArgs` type that provides the following properties:
```suggestion
- `SwipeCompleted`&mdash;Occurs when the swiping of an item is completed. The event arguments are of the `CollectionViewSwipeCompletedEventArgs` type that provides the following properties:
```

2024-07-23 12:12 UTC, ikoevska commented on controls/collectionview/item-swipe/item-swipe-events.md
> +  - `Item`(`object`)&mdash;The item that has been swiped.
```suggestion
  - `Item`(`object`)&mdash;The item that was swiped.
```

2024-07-23 12:12 UTC, ikoevska commented on controls/collectionview/item-swipe/item-swipe-commands.md
> +The .NET MAUI CollectionView provides the  following commands related to swipe actions:
```suggestion
The .NET MAUI CollectionView provides the following commands related to swipe actions:
```

2024-07-23 12:12 UTC, ikoevska commented on controls/collectionview/item-swipe/item-swipe-commands.md
> +- `SwipeStartingCommand`(`ICommand`)&mdash;Occurs when item is about to be swiped. The command parameter is of the `CollectionViewSwipeStartingCommandContext` type that provides the following propert
```suggestion
- `SwipeStartingCommand`(`ICommand`)&mdash;Occurs when an item is about to be swiped. The command parameter is of the `CollectionViewSwipeStartingCommandContext` type that provides the following properties:
```

2024-07-23 12:12 UTC, ikoevska commented on controls/collectionview/item-swipe/item-swipe-commands.md
> +- `ItemSwipeCompleted`(`ICommand`)&mdash;Occurs when swiping of an item is completed. TThe command parameter is of the `CollectionViewSwipeCompletedCommandContext` type that provides the following pr
```suggestion
- `ItemSwipeCompleted`(`ICommand`)&mdash;Occurs when the swiping of an item is completed. The command parameter is of the `CollectionViewSwipeCompletedCommandContext` type that provides the following properties:
```

2024-07-23 12:12 UTC, ikoevska commented on controls/collectionview/item-swipe/item-swipe-commands.md
> +  - `Item`(`object`)&mdash;The item that has been swiped.
```suggestion
  - `Item`(`object`)&mdash;The item that was swiped.
```

2024-07-25 08:58 UTC, kerpecheva commented
Updated section title in config

2024-07-26 07:23 UTC, ikoevska approved these changes

2024-07-26 07:45 UTC, merged